print('Starting Web Page: Time Table Management System')
print('Web Page Changed to : Student Management Companion')
print('Student UI test Passed')
print('Starting Web Page: Time Table Management System')
print('Web Page Changed to : Teacher Management Companion')
print('Teacher UI test Passed')
print('Starting Web Page: Time Table Management System')
print('Web Page Changed to : Admin Management Companion')
print('Admin UI test Passed')
